import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const KNOWN_WEAK_SECRETS = new Set([
  'change-me-to-a-long-random-string',
  'change-me-in-production',
  'replace_with_generated_secret',
  'change-me',
  '',
]);

/**
 * Ensures that JWT_SECRET is set and strong in the gateway's .env file.
 * Mirrors the auto-generation logic from the seller's migrate.ts.
 */
export function ensureEnvSetup(): void {
  const envPath = path.resolve(__dirname, '../../.env');
  const examplePath = path.resolve(__dirname, '../../.env.example');

  // 1. Create .env if missing
  if (!fs.existsSync(envPath)) {
    if (fs.existsSync(examplePath)) {
      fs.copyFileSync(examplePath, envPath);
      console.log('✔  Created .env from .env.example');
    } else {
      fs.writeFileSync(envPath, '# Generated by env-setup.ts\n', 'utf8');
      console.log('✔  Created empty .env file');
    }
  }

  // 2. Load current secret (dotenv is already loaded in main.ts, but we check the file to persist it)
  let envContent = fs.readFileSync(envPath, 'utf8');
  const secretMatch = envContent.match(/^JWT_SECRET=(.*)$/m);
  const currentSecret = secretMatch ? secretMatch[1].trim() : (process.env.JWT_SECRET ?? '');

  if (!currentSecret || currentSecret.length < 32 || KNOWN_WEAK_SECRETS.has(currentSecret.toLowerCase())) {
    const generated = crypto.randomBytes(32).toString('hex');
    const newLine = `JWT_SECRET=${generated}`;
    
    if (secretMatch) {
      envContent = envContent.replace(/^JWT_SECRET=.*$/m, newLine);
    } else {
      envContent += `\n${newLine}\n`;
    }
    
    fs.writeFileSync(envPath, envContent, 'utf8');
    process.env.JWT_SECRET = generated; // Apply to current process
    console.log('✔  Generated and saved strong JWT_SECRET to .env');
  }
}
